version: '3'

vars:
  VERSION: v0.9.0
  COMMIT:
    sh: git rev-parse --short HEAD

tasks:
  default:
    cmds:
      - task: mac
      - task: windows
  dev:
    cmds:
      - wails dev -appargs "-datastore ./tmp/ -syslogPort 8514 -trapPort 8162"
  deven:
    cmds:
      - wails dev -appargs "-datastore ./tmp/ -syslogPort 8514 -trapPort 8162 -lang en"
  mac:
    cmds:
      - wails build  -platform darwin/universal -ldflags "-s -w -X main.version={{.VERSION}} -X main.commit={{.COMMIT}}"
  macdebug:
    cmds:
      - wails build  -platform darwin -debug -clean -ldflags "-s -w -X main.version={{.VERSION}} -X main.commit={{.COMMIT}}"
  windows:
    cmds:
      - wails build  -platform windows/amd64 -nsis -ldflags "-s -w -X main.version={{.VERSION}} -X main.commit={{.COMMIT}}"
  windebug:
    cmds:
      - wails build  -platform windows/amd64 -debug -clean -windowsconsole -ldflags "-s -w -X main.version={{.VERSION}} -X main.commit={{.COMMIT}}"
  clean:
    cmds:
      - rm -rf build/bin/twsnmpfk*
