version: '3'

vars:
  VERSION: v2.4.0
  COMMIT:
    sh: git rev-parse --short HEAD
  TAGS: wgpu24

env:
  GOEXPERIMENT: simd

tasks:
  default:
    cmds:
      - task: windows
      - task: mac
  dev:
    cmds:
      - wails dev -tags {{.TAGS}} -appargs "-datastore ./tmp/"
  dev_discover:
    cmds:
      - wails dev -tags {{.TAGS}} -appargs "-datastore /tmp/twsnmpfk/"
  deven:
    cmds:
      - wails dev -tags {{.TAGS}} -appargs "-datastore ./tmp/ -lang en"
  devens:
    cmds:
      - wails dev -tags {{.TAGS}} -appargs "-lang en"
  mac:
    cmds:
      - wails build  -platform darwin/universal -tags {{.TAGS}} -ldflags "-s -w -X main.version={{.VERSION}} -X main.commit={{.COMMIT}}"
  macdebug:
    cmds:
      - wails build  -platform darwin -debug -clean -tags {{.TAGS}} -ldflags "-s -w -X main.version={{.VERSION}} -X main.commit={{.COMMIT}}"
  linux:
    cmds:
      - wails build -clean -platform linux/amd64 -tags "webkit2_41,{{.TAGS}}" -ldflags "-s -w -X main.version={{.VERSION}} -X main.commit={{.COMMIT}}"
  windows:
    cmds:
      - wails build -clean -webview2 Browser -platform windows/amd64 -nsis -tags {{.TAGS}} -ldflags "-s -w -X main.version={{.VERSION}} -X main.commit={{.COMMIT}}"
  windebug:
    cmds:
      - wails build  -platform windows/amd64 -debug -clean -windowsconsole -tags {{.TAGS}} -ldflags "-s -w -X main.version={{.VERSION}} -X main.commit={{.COMMIT}}"
  clean:
    cmds:
      - rm -rf build/bin/twsnmpfk*
