version: '3'

vars:
  VERSION: v1.27.0
  COMMIT:
    sh: git rev-parse --short HEAD

tasks:
  default:
    cmds:
      - task: windows
      - task: mac
  dev:
    cmds:
      - wails dev -appargs "-datastore ./tmp/"
  deven:
    cmds:
      - wails dev -appargs "-datastore ./tmp/ -lang en"
  devens:
    cmds:
      - wails dev -appargs "-lang en"
  mac:
    cmds:
      - wails build  -platform darwin/universal -ldflags "-s -w -X main.version={{.VERSION}} -X main.commit={{.COMMIT}}"
  macdebug:
    cmds:
      - wails build  -platform darwin -debug -clean -ldflags "-s -w -X main.version={{.VERSION}} -X main.commit={{.COMMIT}}"
  windows:
    cmds:
      - wails build -clean -webview2 Browser -platform windows/amd64 -nsis -ldflags "-s -w -X main.version={{.VERSION}} -X main.commit={{.COMMIT}}"
  windebug:
    cmds:
      - wails build  -platform windows/amd64 -debug -clean -windowsconsole -ldflags "-s -w -X main.version={{.VERSION}} -X main.commit={{.COMMIT}}"
  clean:
    cmds:
      - rm -rf build/bin/twsnmpfk*
