// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPolling(arg1) {
  return window['go']['main']['App']['CheckPolling'](arg1);
}

export function CopyDrawItem(arg1) {
  return window['go']['main']['App']['CopyDrawItem'](arg1);
}

export function CopyNode(arg1) {
  return window['go']['main']['App']['CopyNode'](arg1);
}

export function DeeleteAIResult(arg1) {
  return window['go']['main']['App']['DeeleteAIResult'](arg1);
}

export function DeleteDrawItems(arg1) {
  return window['go']['main']['App']['DeleteDrawItems'](arg1);
}

export function DeleteLine(arg1) {
  return window['go']['main']['App']['DeleteLine'](arg1);
}

export function DeleteNodes(arg1) {
  return window['go']['main']['App']['DeleteNodes'](arg1);
}

export function DeletePollings(arg1) {
  return window['go']['main']['App']['DeletePollings'](arg1);
}

export function ExportEventLogs(arg1) {
  return window['go']['main']['App']['ExportEventLogs'](arg1);
}

export function ExportNodes(arg1) {
  return window['go']['main']['App']['ExportNodes'](arg1);
}

export function ExportPollings(arg1) {
  return window['go']['main']['App']['ExportPollings'](arg1);
}

export function ExportSyslogs(arg1) {
  return window['go']['main']['App']['ExportSyslogs'](arg1);
}

export function ExportTraps(arg1) {
  return window['go']['main']['App']['ExportTraps'](arg1);
}

export function GetAIConf() {
  return window['go']['main']['App']['GetAIConf']();
}

export function GetAIList() {
  return window['go']['main']['App']['GetAIList']();
}

export function GetAIResult(arg1) {
  return window['go']['main']['App']['GetAIResult'](arg1);
}

export function GetAlertEventLogs() {
  return window['go']['main']['App']['GetAlertEventLogs']();
}

export function GetBackImage() {
  return window['go']['main']['App']['GetBackImage']();
}

export function GetDiscoverConf() {
  return window['go']['main']['App']['GetDiscoverConf']();
}

export function GetDiscoverStats() {
  return window['go']['main']['App']['GetDiscoverStats']();
}

export function GetDrawItem(arg1) {
  return window['go']['main']['App']['GetDrawItem'](arg1);
}

export function GetDrawItems() {
  return window['go']['main']['App']['GetDrawItems']();
}

export function GetEventLogs(arg1) {
  return window['go']['main']['App']['GetEventLogs'](arg1);
}

export function GetGroks() {
  return window['go']['main']['App']['GetGroks']();
}

export function GetImage(arg1) {
  return window['go']['main']['App']['GetImage'](arg1);
}

export function GetLine(arg1, arg2) {
  return window['go']['main']['App']['GetLine'](arg1, arg2);
}

export function GetLines() {
  return window['go']['main']['App']['GetLines']();
}

export function GetMapConf() {
  return window['go']['main']['App']['GetMapConf']();
}

export function GetMapName() {
  return window['go']['main']['App']['GetMapName']();
}

export function GetNode(arg1) {
  return window['go']['main']['App']['GetNode'](arg1);
}

export function GetNodes() {
  return window['go']['main']['App']['GetNodes']();
}

export function GetNotifyConf() {
  return window['go']['main']['App']['GetNotifyConf']();
}

export function GetPolling(arg1) {
  return window['go']['main']['App']['GetPolling'](arg1);
}

export function GetPollings(arg1) {
  return window['go']['main']['App']['GetPollings'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSyslogs() {
  return window['go']['main']['App']['GetSyslogs']();
}

export function GetTraps() {
  return window['go']['main']['App']['GetTraps']();
}

export function GetVPanelPorts(arg1) {
  return window['go']['main']['App']['GetVPanelPorts'](arg1);
}

export function GetVPanelPowerInfo(arg1) {
  return window['go']['main']['App']['GetVPanelPowerInfo'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function SelectFile(arg1, arg2) {
  return window['go']['main']['App']['SelectFile'](arg1, arg2);
}

export function StartDiscover(arg1) {
  return window['go']['main']['App']['StartDiscover'](arg1);
}

export function StopDiscover() {
  return window['go']['main']['App']['StopDiscover']();
}

export function TestNotifyConf(arg1) {
  return window['go']['main']['App']['TestNotifyConf'](arg1);
}

export function UpdateAIConf(arg1) {
  return window['go']['main']['App']['UpdateAIConf'](arg1);
}

export function UpdateDrawItem(arg1) {
  return window['go']['main']['App']['UpdateDrawItem'](arg1);
}

export function UpdateDrawItemPos(arg1) {
  return window['go']['main']['App']['UpdateDrawItemPos'](arg1);
}

export function UpdateLine(arg1) {
  return window['go']['main']['App']['UpdateLine'](arg1);
}

export function UpdateMapConf(arg1) {
  return window['go']['main']['App']['UpdateMapConf'](arg1);
}

export function UpdateNode(arg1) {
  return window['go']['main']['App']['UpdateNode'](arg1);
}

export function UpdateNodePos(arg1) {
  return window['go']['main']['App']['UpdateNodePos'](arg1);
}

export function UpdateNotifyConf(arg1) {
  return window['go']['main']['App']['UpdateNotifyConf'](arg1);
}

export function UpdatePolling(arg1) {
  return window['go']['main']['App']['UpdatePolling'](arg1);
}

export function WakeOnLan(arg1) {
  return window['go']['main']['App']['WakeOnLan'](arg1);
}
