// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {datastore} from '../models';
import {main} from '../models';

export function GetAIConf():Promise<datastore.AIConfEnt>;

export function GetBackImage():Promise<datastore.BackImageEnt>;

export function GetDrawItems():Promise<{[key: string]: datastore.DrawItemEnt}>;

export function GetLastEventLogs(arg1:number):Promise<Array<datastore.EventLogEnt>>;

export function GetLines():Promise<Array<datastore.LineEnt>>;

export function GetMapConf():Promise<datastore.MapConfEnt>;

export function GetNodes():Promise<{[key: string]: datastore.NodeEnt}>;

export function GetNotifyConf():Promise<datastore.NotifyConfEnt>;

export function GetSettings():Promise<main.Settings>;

export function GetVersion():Promise<string>;

export function SetAIConf(arg1:datastore.AIConfEnt):Promise<boolean>;

export function SetMapConf(arg1:datastore.MapConfEnt):Promise<boolean>;

export function SetNotifyConf(arg1:datastore.NotifyConfEnt):Promise<boolean>;

export function TestNotifyConf(arg1:datastore.NotifyConfEnt):Promise<boolean>;
