// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}
